#!/usr/bin/python3

list =[11,82,7,1,1,30,0,]
print(list)
list2 = list.copy()
print("\nCopy All Elements in Another List2 :\n",list2)
list.append(24)
print("\nInsert Item in Last Index :\n",list)
print("\nReturn index of you Searching Item :\n",list.index(30))
list.sort()
print("\nSort the Numbers Assending order :\n",list)
list.pop()
print("\nDelete Number of the Last Index :\n",list)
list.pop(4)
print("\nDelete the Item of index 4 is 11 \n",list)
list.remove(7)
print("\nRemove the Element You Want :\n",list)
list.insert(1,2)
print("\nin index 1 Add Number : 2 \n",list)
list.reverse()
print("\nReverse Numbers : \n",list)
print("\nCount Numbers of 1 in list : \n",list.count(1))
list.clear()
print("\nDelete all List Numbers : \n",list)
list.append("Fardin")
print("\nInsert My Name :\n",list)
list.extend(["Shaikh"])
print("\nAdd Items :\n",list)
list.extend((10,20,30))
print(list)
list.extend("Prince")
print("\n",list)

